### ISSUE TITLE
Ignore packages

### ISSUE THREAD

**Issue by S4n60w3n** [webscopeio/license.sh#41]
One should be able to ignore packages.

Lets say test is not able to resolve certain license. However, I am able to find online its license and confirm that it is ok for my scenario. I should be able to add it to config file to prevent further fails.

```
ignore: [
'package-utils@1.0.0',
'random@1.2.3'
]
```

**Comment by S4n60w3n** [comment]
@jvorcak WDYT?

**Comment by jvorcak** [comment]
@S4n60w3n I'm on it

**Comment by jvorcak** [comment]
@S4n60w3n @jankoritak I suggest the following structure in the config

```
 "ignored_packages": {
    "python_pipenv": [
      "PyInquirer",
      "setuptools"
    ],
    "npm": [],
    "maven": [],
    "yarn": []
  }
```

For now we will support excluding only the whole packages, not specific versions. WDYT?
