### ISSUE TITLE
Replace PyInquirer

### ISSUE THREAD

**Issue by jayvdb** [webscopeio/license.sh#42]
PyInquirer requires prompt_toolkit 1.x , which is now incompatible with most other parts of the Python ecosystem, and it appears unlikely to become prompt_toolkit 2.x compatible any time soon.

https://github.com/tmbo/questionary was created by people who have given up waiting for PyInquirer to become prompt_toolkit 2.x compatible.

**Comment by jvorcak** [comment]
@jayvdb Thanks for the input. I'll have a look at this asap.

**Comment by jvorcak** [comment]
@jayvdb https://github.com/webscopeio/license.sh/pull/44, feel free to review
