### ISSUE TITLE
Add __main__

### ISSUE THREAD

**Issue by jayvdb** [webscopeio/license.sh#49]
```
> python3 -m license_sh
/usr/bin/python3: No module named license_sh.__main__; 'license_sh' is a package and cannot be directly executed
```

**Comment by jayvdb** [comment]
This is require the logic in the script to move into the package, which has the benefit of also making it easier to test.

**Comment by jvorcak** [comment]
Good point 👍 thanks. This requires cleaning up some code and moving it along, I'll deal with this once #44 and #46 PRs are merged to avoid possible conflicts.

**Comment by jvorcak** [comment]
<img width="439" alt="Screenshot 2019-12-21 at 15 35 35" src="https://user-images.githubusercontent.com/1083817/71309398-90be8f00-2407-11ea-85d2-ee885bdb8fc9.png">

This should now work with `1.0.11` release. Thanks for the input!
